import base64
import json
from datetime import datetime, timezone
from typing import Protocol
from urllib import request
from urllib.error import HTTPError, URLError
from uuid import uuid4

from app.models.schemas import JiraTicket


class JiraClient(Protocol):
    def create_ticket(self, summary: str, description: str, labels: list[str]) -> JiraTicket:
        ...


class MockJiraClient:
    def __init__(self, project_key: str = "SUP") -> None:
        self.project_key = project_key

    def create_ticket(self, summary: str, description: str, labels: list[str]) -> JiraTicket:
        suffix = str(uuid4()).split("-")[0].upper()
        ticket_key = f"{self.project_key}-{suffix}"
        enriched_description = (
            f"{description}\n\nGenerated by support agent at {datetime.now(timezone.utc).isoformat()}"
        )
        return JiraTicket(
            key=ticket_key,
            summary=summary,
            description=enriched_description,
            labels=labels,
        )


class RealJiraClient:
    def __init__(
        self,
        base_url: str,
        project_key: str,
        email: str,
        api_token: str,
        timeout_seconds: int = 20,
    ) -> None:
        self.base_url = base_url.rstrip("/")
        self.project_key = project_key
        self.email = email
        self.api_token = api_token
        self.timeout_seconds = timeout_seconds

        if not all([self.base_url, self.project_key, self.email, self.api_token]):
            raise ValueError("Jira config is incomplete for real integration")

    def create_ticket(self, summary: str, description: str, labels: list[str]) -> JiraTicket:
        url = f"{self.base_url}/rest/api/3/issue"
        payload = {
            "fields": {
                "project": {"key": self.project_key},
                "summary": summary,
                "description": {
                    "type": "doc",
                    "version": 1,
                    "content": [
                        {
                            "type": "paragraph",
                            "content": [{"type": "text", "text": description}],
                        }
                    ],
                },
                "issuetype": {"name": "Task"},
                "labels": labels,
            }
        }

        token = base64.b64encode(f"{self.email}:{self.api_token}".encode("utf-8")).decode("ascii")
        req = request.Request(
            url=url,
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Basic {token}",
                "Content-Type": "application/json",
                "Accept": "application/json",
            },
            method="POST",
        )

        try:
            with request.urlopen(req, timeout=self.timeout_seconds) as resp:
                body = resp.read().decode("utf-8")
                parsed = json.loads(body)
        except HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="ignore") if exc.fp else ""
            raise RuntimeError(f"Jira API error {exc.code}: {detail}") from exc
        except URLError as exc:
            raise RuntimeError(f"Jira connection error: {exc.reason}") from exc

        key = parsed.get("key")
        if not key:
            raise RuntimeError("Jira API response missing issue key")

        return JiraTicket(
            key=key,
            summary=summary,
            description=description,
            labels=labels,
        )
